"use client"
import { useEffect, useMemo, useState, useCallback, useRef } from 'react'
type LatLng={lat:number;lng:number}
type Offer={id:number;title:string;store:string;logo:string;category:string;price:number;old_price:number;discount:number;image:string;views:number;rating:number;endAt:string;createdAt:string;barcode?:string;location:LatLng&{address:string;district:string}}
const GOLD_DARK="#7A5A16"
const OFFERS_INIT:Offer[]=[
{id:1,title:'عطر حكيم الملكي 100مل',store:'متجر حكيم',logo:'💛',category:'عطور',price:199,old_price:349,discount:43,image:'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600',views:5420,rating:4.8,endAt:new Date(Date.now()+4836001000).toISOString(),createdAt:new Date().toISOString(),barcode:'6281000012345',location:{lat:21.5439,lng:39.1731,address:'الروضة، جدة',district:'الروضة'}},
{id:2,title:'مكيف سبيلت 18000 وحدة',store:'إكسترا',logo:'🔌',category:'إلكترونيات',price:1899,old_price:2899,discount:34,image:'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600',views:3210,rating:4.6,endAt:new Date(Date.now()+536001000).toISOString(),createdAt:new Date().toISOString(),barcode:'8801643870457',location:{lat:21.5522,lng:39.158,address:'التحلية، جدة',district:'الأندلس'}},
{id:3,title:'سلة التوفير - بنده',store:'بنده',logo:'🛒',category:'سوبرماركت',price:89,old_price:149,discount:40,image:'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600',views:8920,rating:4.4,endAt:new Date(Date.now()+2036001000).toISOString(),createdAt:new Date().toISOString(),barcode:'6281017401006',location:{lat:21.5796,lng:39.1321,address:'فلسطين، جدة',district:'الحمراء'}},
{id:4,title:'جوال ايفون 15 - 128GB',store:'جرير',logo:'📱',category:'إلكترونيات',price:3299,old_price:3899,discount:15,image:'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=600',views:4120,rating:4.9,endAt:new Date(Date.now()+2836001000).toISOString(),createdAt:new Date().toISOString(),barcode:'194252707234',location:{lat:21.56,lng:39.17,address:'ردسي مول',district:'الشاطئ'}},
{id:5,title:'عطر مسك العود الفاخر',store:'متجر حكيم',logo:'💛',category:'عطور',price:249,old_price:399,discount:37,image:'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600',views:2100,rating:4.7,endAt:new Date(Date.now()+3836001000).toISOString(),createdAt:new Date().toISOString(),barcode:'6281000023456',location:{lat:21.39,lng:39.86,address:'العزيزية، مكة',district:'العزيزية'}},
{id:6,title:'قلاية هوائية 5.5 لتر',store:'إكسترا',logo:'🔌',category:'إلكترونيات',price:299,old_price:549,discount:45,image:'https://images.unsplash.com/photo-1585515656512-3c6a2a9a0b1a?w=600',views:3300,rating:4.5,endAt:new Date(Date.now()+1836001000).toISOString(),createdAt:new Date().toISOString(),barcode:'6925280810825',location:{lat:24.71,lng:46.67,address:'العليا، الرياض',district:'العليا'}},
]
function haversine(a:LatLng,b:LatLng){const R=6371;const dLat=(b.lat-a.lat)*Math.PI/180;const dLng=(b.lng-a.lng)*Math.PI/180;const s=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(s))}
const formatPrice=(n:number)=>`${n.toLocaleString('ar-SA')} ر.س`
const formatDistance=(k:number)=>k<1?`${Math.round(k*1000)} م`:`${k.toFixed(1)} كم`
function useCountdown(end:string){const [t,setT]=useState('');useEffect(()=>{const fn=()=>{const d=new Date(end).getTime()-Date.now();if(d<=0){setT('انتهى');return}const h=Math.floor(d/36e5);const m=Math.floor(d%36e5/6e4);if(h>=24)setT(`${Math.floor(h/24)} يوم`);else setT(`${h}س ${m}د`)};fn();const id=setInterval(fn,60000);return()=>clearInterval(id)},[end]);return t}
export default function Page(){
const [offers,setOffers]=useState<Offer[]>(OFFERS_INIT)
const [userLoc,setUserLoc]=useState<LatLng|null>(null)
const [query,setQuery]=useState('');const [favs,setFavs]=useState<number[]>([]);const [showFavs,setShowFavs]=useState(false)
const [toast,setToast]=useState('');const [imgPrev,setImgPrev]=useState<string|null>(null);const [imgActive,setImgActive]=useState(false)
const [isListening,setIsListening]=useState(false);const [assistantOpen,setAssistantOpen]=useState(false);const [assistantInput,setAssistantInput]=useState('');const [assistantMsgs,setAssistantMsgs]=useState<{role:'user'|'bot',text:string}[]>([{role:'bot',text:'هلا! أسألني: وين أرخص قلاية؟ أو صور باركود'}])
const [mapOpen,setMapOpen]=useState(false);const [merchantOpen,setMerchantOpen]=useState(false);const [scannerOpen,setScannerOpen]=useState(false);const [scanResult,setScanResult]=useState<string>('')
const [newOffer,setNewOffer]=useState({title:'',price:'',store:'متجر حكيم',category:'عطور',image:''})
const fileRef=useRef<HTMLInputElement>(null);const mapRef=useRef<HTMLDivElement>(null);const videoRef=useRef<HTMLVideoElement>(null)
const showToast=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),3500)}
useEffect(()=>{try{const f=localStorage.getItem('hkeeem_favs');if(f)setFavs(JSON.parse(f));const o=localStorage.getItem('hkeeem_offers_v3');if(o)setOffers(JSON.parse(o));const l=localStorage.getItem('hkeeem_user_location');if(l)setUserLoc(JSON.parse(l))}catch{}if('Notification'in window&&Notification.permission==='default')Notification.requestPermission()},[])
useEffect(()=>{try{localStorage.setItem('hkeeem_favs',JSON.stringify(favs))}catch{}},[favs])
useEffect(()=>{try{localStorage.setItem('hkeeem_offers_v3',JSON.stringify(offers))}catch{}},[offers])
const refPoint=useMemo(()=>userLoc?userLoc:null,[userLoc])
const offersWithDist=useMemo(()=>{if(!refPoint)return offers.map(o=>({...o,distance:null as number|null}));return offers.map(o=>({...o,distance:haversine(refPoint,o.location)})).sort((a,b)=>(a.distance??999)-(b.distance??999))},[refPoint,offers])
const filtered=useMemo(()=>{let a=[...offersWithDist]as any[];if(imgActive)a=a.filter(o=>o.category==='عطور');if(query.trim()){const q=query.toLowerCase();a=a.filter(o=>(o.title+o.store+o.category+(o.barcode||'')).toLowerCase().includes(q))}if(showFavs)a=a.filter(o=>favs.includes(o.id));return a},[offersWithDist,query,showFavs,favs,imgActive])
useEffect(()=>{if(!userLoc)return;const near=offersWithDist.filter((o:any)=>o.distance!==null&&o.distance<0.8);if(near.length>0){const n=near[0]as any;showToast(`🔔 قريب منك: ${n.title} على بعد ${formatDistance(n.distance)} - وفر ${n.discount}%`);if('Notification'in window&&Notification.permission==='granted'){new Notification('عرض قريب منك! 📍',{body:`${n.title} - ${formatPrice(n.price)}`})}}},[userLoc,offersWithDist])
useEffect(()=>{if(!mapOpen||!mapRef.current||!userLoc)return;const L:any=(window as any).L;if(!L){const link=document.createElement('link');link.rel='stylesheet';link.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(link);const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=()=>initMap();document.body.appendChild(s);}else initMap();function initMap(){const L2=(window as any).L;if(!mapRef.current)return;mapRef.current.innerHTML='';const map=L2.map(mapRef.current).setView([userLoc!.lat,userLoc!.lng],13);L2.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);L2.marker([userLoc!.lat,userLoc!.lng]).addTo(map).bindPopup('موقعك أنت 📍').openPopup();offersWithDist.slice(0,10).forEach((o:any)=>{L2.marker([o.location.lat,o.location.lng]).addTo(map).bindPopup(`${o.title}<br>${formatPrice(o.price)}`)})}},[mapOpen,userLoc,offersWithDist])
const fetchLocation=useCallback(()=>{navigator.geolocation.getCurrentPosition(p=>{const l={lat:p.coords.latitude,lng:p.coords.longitude};setUserLoc(l);localStorage.setItem('hkeeem_user_location',JSON.stringify(l));showToast('تم تحديد موقعك ✅ الخريطة والتنبيهات اشتغلت')},()=>showToast('فعل الـ GPS'),{enableHighAccuracy:true})},[])
const handleImageUpload=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f);setImgPrev(url);setImgActive(true);setTimeout(()=>{setQuery('عطر');showToast('📷 وجدنا عطور مشابهة')},900)}
const startVoice=()=>{const SR=(window as any).webkitSpeechRecognition||(window as any).SpeechRecognition;if(!SR){showToast('المتصفح لا يدعم الصوت');return}const r=new SR();r.lang='ar-SA';setIsListening(true);r.start();r.onresult=(ev:any)=>{setQuery(ev.results[0][0].transcript);setIsListening(false);showToast(`🎤 ${ev.results[0][0].transcript}`)};r.onend=()=>setIsListening(false)}
const askAssistant=()=>{if(!assistantInput.trim())return;const q=assistantInput;setAssistantMsgs(m=>[...m,{role:'user',text:q}]);setAssistantInput('');setTimeout(()=>{let a='';const low=q.toLowerCase();if(low.includes('ارخص')){const c=[...offers].sort((x,y)=>x.price-y.price)[0];a=`أرخص عرض هو ${c.title} بـ ${formatPrice(c.price)} في ${c.store} 🔥`}else if(low.includes('قريب')||low.includes('وين')){const c=offersWithDist[0]as any;a=c.distance?`أقرب لك: ${c.title} على بعد ${formatDistance(c.distance)}`:`فعل الموقع أول 📍`}else if(low.includes('باركود')||low.includes('سكانر')){a='افتح زر الباركود 📷 وصور أي منتج وأنا أقارن لك السعر فوراً'}else{a=`أقدر أساعدك: 1- وين أرخص ${q}؟ 2- عروض قريبة مني؟ 3- صور باركود وقارن`}setAssistantMsgs(m=>[...m,{role:'bot',text:a}])},400)}
const addOffer=()=>{if(!newOffer.title||!newOffer.price){showToast('عبي الاسم والسعر');return}const o:Offer={id:Date.now(),title:newOffer.title,store:newOffer.store,logo:'🏪',category:newOffer.category,price:parseInt(newOffer.price),old_price:Math.round(parseInt(newOffer.price)*1.4),discount:30,image:newOffer.image||'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600',views:0,rating:5,endAt:new Date(Date.now()+172800000).toISOString(),createdAt:new Date().toISOString(),location:{lat:userLoc?.lat||21.5433,lng:userLoc?.lng||39.1727,address:'موقع التاجر',district:'الروضة'}};setOffers(v=>[o,...v]);setMerchantOpen(false);setNewOffer({title:'',price:'',store:'متجر حكيم',category:'عطور',image:''});showToast('✅ تم نشر عرضك! صار يظهر للكل')}
const startScanner=async()=>{setScannerOpen(true);setScanResult('');try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});if(videoRef.current){videoRef.current.srcObject=stream;videoRef.current.play();const BD=(window as any).BarcodeDetector;if(BD){const det=new BD({formats:['ean_13','ean_8','qr_code']});const loop=setInterval(async()=>{try{const codes=await det.detect(videoRef.current);if(codes.length>0){clearInterval(loop);const val=codes[0].rawValue;handleBarcode(val);(stream.getTracks()[0]as any).stop()}}catch{}},800)}}}catch{showToast('الكاميرا تحتاج HTTPS وسماح')}}
const handleBarcode=(code:string)=>{setScanResult(code);setScannerOpen(false);const found=offers.find(o=>o.barcode===code);if(found){setQuery(code);showToast(`✅ لقيناه! ${found.title} بـ ${formatPrice(found.price)}`);}else{const similar=offers.filter(o=>o.category==='سوبرماركت').sort((a,b)=>a.price-b.price)[0];setQuery('');showToast(`🔍 الباركود ${code} - أرخص بديل: ${similar.title} بـ ${formatPrice(similar.price)}`);setAssistantMsgs(m=>[...m,{role:'bot',text:`سكانر: ${code} - ما لقيناه بالضبط، لكن أقترح ${similar.title}`}]);setAssistantOpen(true)}if(videoRef.current?.srcObject){(videoRef.current.srcObject as any).getTracks().forEach((t:any)=>t.stop())}}
return(
<div className="min-h-screen pb-28 bg-[#FDF6E8] text-[#1F1B16]" dir="rtl">
<header className="sticky top-0 z-30 bg-white/95 backdrop-blur-xl border-b"><div className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between"><div className="flex items-center gap-2"><img src="/Hkeeem_logo_en-2.png" alt="" className="w-10 h-10 rounded-xl bg-white border p-1"/><span className="font-black">عروض<span style={{color:GOLD_DARK}}>كم</span></span><span className="bg-black text-white px-2 py-0.5 rounded-full text-[10px] font-black">V3 🌍🏪📷</span></div><div className="flex gap-1"><button onClick={()=>setMapOpen(v=>!v)} className={`w-9 h-9 rounded-full grid place-items-center border ${mapOpen?'bg-black text-white':'bg-white'}`}>🗺️</button><button onClick={()=>setMerchantOpen(true)} className="w-9 h-9 rounded-full bg-white border grid place-items-center">🏪</button><button onClick={fetchLocation} className="px-3 h-9 rounded-full bg-black text-white text-xs font-black">📍</button></div></div></header>
<main className="max-w-6xl mx-auto px-4">
<div className="mt-3 flex gap-2"><div className="flex-1 relative"><input value={query} onChange={e=>{setQuery(e.target.value);setImgActive(false);setImgPrev(null)}} placeholder="ابحث، احكي، أو صور باركود..." className="w-full h-12 pr-10 pl-28 rounded-2xl border-2 border-[#EADFC9] bg-white outline-none text-sm"/><span className="absolute right-3 top-1/2 -translate-y-1/2">🔍</span><div className="absolute left-1.5 top-1/2 -translate-y-1/2 flex gap-1"><button onClick={()=>fileRef.current?.click()} className="w-9 h-9 rounded-full bg-[#FFF8E6] border grid place-items-center">📷</button><button onClick={startVoice} className={`w-9 h-9 rounded-full border grid place-items-center ${isListening?'bg-red-500 text-white':'bg-white'}`}>🎤</button><button onClick={startScanner} className="w-9 h-9 rounded-full bg-black text-white grid place-items-center">📦</button></div></div></div>
<input ref={fileRef} type="file" accept="image/*" hidden onChange={handleImageUpload}/>
{imgPrev&&<div className="mt-2 p-2 bg-white border rounded-xl flex gap-2 items-center"><img src={imgPrev} className="w-14 h-14 rounded object-cover"/><span className="text-xs font-bold">بحث بالصورة نشط</span><button onClick={()=>{setImgPrev(null);setImgActive(false)}} className="mr-auto text-xs bg-zinc-100 px-2 py-1 rounded-full">إلغاء</button></div>}
{mapOpen&&<div className="mt-3 rounded-2xl overflow-hidden border-2 border-[#E9C86A] h-72 bg-zinc-100 relative"><div ref={mapRef} className="w-full h-full"></div>{!userLoc&&<div className="absolute inset-0 grid place-items-center bg-white/80"><button onClick={fetchLocation} className="px-4 h-10 rounded-full bg-black text-white text-sm">فعل الموقع لعرض الخريطة 🗺️</button></div>}</div>}
<div className="mt-3 flex gap-2 overflow-x-auto pb-1">{['الكل','عطور','إلكترونيات','سوبرماركت'].map(c=><button key={c} onClick={()=>setQuery(c==='الكل'?'':c)} className={`px-4 h-8 rounded-full text-xs font-black border whitespace-nowrap ${query===c||(c==='الكل'&&!query)?'bg-black text-white':'bg-white'}`}>{c}</button>)}<button onClick={()=>setShowFavs(v=>!v)} className={`mr-auto px-3 h-8 rounded-full text-xs font-black border ${showFavs?'bg-[#FFF3CC]':''}`}>❤️ المفضلة</button></div>
{scanResult&&<div className="mt-3 p-3 rounded-2xl bg-green-50 border border-green-200 text-sm">📦 نتيجة السكانر: <b>{scanResult}</b> - تمت المقارنة تلقائياً</div>}
<section className="mt-3 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">{filtered.map((o:any)=>{const cd=useCountdown(o.endAt);const fav=favs.includes(o.id);return(<article key={o.id} className="rounded-2xl bg-white border overflow-hidden shadow-sm flex flex-col"><div className="relative"><img src={o.image} className="h-44 w-full object-cover"/><span className="absolute top-2 right-2 px-2 py-1 rounded-full bg-black text-white text-[11px] font-black">-{o.discount}%</span><button onClick={()=>{const n=fav?favs.filter(x=>x!==o.id):[...favs,o.id];setFavs(n)}} className="absolute top-2 left-2 w-8 h-8 rounded-full bg-white grid place-items-center shadow">{fav?'❤️':'🤍'}</button>{o.distance!=null&&<span className="absolute bottom-2 left-2 px-2 py-0.5 rounded-full bg-black/80 text-white text-[11px]">📍 {formatDistance(o.distance)}</span>}</div><div className="p-3 flex-1 flex flex-col"><h3 className="font-bold text-[13px] line-clamp-2 min-h-9">{o.title}</h3><div className="mt-1 flex items-center gap-2"><b style={{color:GOLD_DARK}}>{formatPrice(o.price)}</b><s className="text-[11px] text-zinc-400">{formatPrice(o.old_price)}</s></div><div className="mt-1 text-[11px]"><span className="px-2 py-0.5 rounded-full bg-red-50 border border-red-200 text-red-600">⏳ {cd}</span><span className="mr-2 text-zinc-500">📦 {o.barcode?.slice(-4)}</span></div><div className="mt-auto pt-2 flex gap-2"><button onClick={()=>window.open(`https://www.google.com/maps/dir/?api=1&destination=${o.location.lat},${o.location.lng}`,'_blank')} className="flex-1 h-9 rounded-full bg-black text-white text-xs font-bold">الوصول 🚗</button><button onClick={()=>{setQuery(o.barcode||'');showToast('تم نسخ الباركود للمقارنة')}} className="w-9 h-9 rounded-full bg-zinc-100 border grid place-items-center">📦</button></div></div></article>)})}</section>
{filtered.length===0&&<div className="mt-10 text-center text-zinc-500 text-sm">ما لقينا شي - جرب كلمة ثانية أو صور باركود</div>}
</main>
{merchantOpen&&<div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm grid place-items-center p-4"><div className="w-full max-w-sm bg-white rounded-3xl p-5"><h3 className="font-black text-lg">🏪 لوحة التاجر - أضف عرضك</h3><p className="text-xs text-zinc-500 mt-1">العرض بينحفظ ويظهر للكل فوراً + على الخريطة</p><div className="mt-4 space-y-3"><input value={newOffer.title} onChange={e=>setNewOffer({...newOffer,title:e.target.value})} placeholder="اسم المنتج" className="w-full h-11 border-2 rounded-xl px-3 text-sm"/><div className="flex gap-2"><input value={newOffer.price} onChange={e=>setNewOffer({...newOffer,price:e.target.value})} placeholder="السعر" type="number" className="flex-1 h-11 border-2 rounded-xl px-3 text-sm"/><select value={newOffer.category} onChange={e=>setNewOffer({...newOffer,category:e.target.value})} className="flex-1 h-11 border-2 rounded-xl px-2 text-sm"><option>عطور</option><option>إلكترونيات</option><option>سوبرماركت</option></select></div><input value={newOffer.image} onChange={e=>setNewOffer({...newOffer,image:e.target.value})} placeholder="رابط الصورة (اختياري)" className="w-full h-11 border-2 rounded-xl px-3 text-sm"/><input value={newOffer.store} onChange={e=>setNewOffer({...newOffer,store:e.target.value})} placeholder="اسم متجرك" className="w-full h-11 border-2 rounded-xl px-3 text-sm"/></div><div className="mt-5 flex gap-2"><button onClick={()=>setMerchantOpen(false)} className="flex-1 h-11 rounded-full bg-zinc-100 font-bold">إلغاء</button><button onClick={addOffer} className="flex-1 h-11 rounded-full bg-black text-white font-black">نشر العرض 🚀</button></div></div></div>}
{scannerOpen&&<div className="fixed inset-0 z-50 bg-black grid place-items-center p-4"><div className="w-full max-w-sm"><div className="rounded-2xl overflow-hidden bg-zinc-900 aspect-[3/4] relative"><video ref={videoRef} className="w-full h-full object-cover"></video><div className="absolute inset-0 border-2 border-white/30 m-10 rounded-xl"></div><div className="absolute top-4 left-4 right-4 flex justify-between"><span className="bg-black/70 text-white px-3 py-1 rounded-full text-xs">وجه الكاميرا على الباركود</span><button onClick={()=>{setScannerOpen(false);if(videoRef.current?.srcObject){(videoRef.current.srcObject as any).getTracks().forEach((t:any)=>t.stop())}}} className="w-8 h-8 rounded-full bg-white grid place-items-center">✕</button></div></div><div className="mt-3 flex gap-2"><input value={scanResult} onChange={e=>setScanResult(e.target.value)} placeholder="أو اكتب الباركود يدوياً" className="flex-1 h-11 rounded-full px-4 text-sm"/><button onClick={()=>handleBarcode(scanResult||'6281000012345')} className="px-5 h-11 rounded-full bg-white text-black font-black text-sm">مقارنة</button></div></div></div>}
<button onClick={()=>setAssistantOpen(v=>!v)} className="fixed bottom-5 left-5 w-14 h-14 rounded-full bg-black text-white text-2xl shadow-2xl grid place-items-center z-40 border-2 border-[#E9C86A]">{assistantOpen?'✕':'🤖'}</button>
{assistantOpen&&<div className="fixed bottom-24 left-4 right-4 md:left-5 md:right-auto md:w-96 rounded-3xl bg-white border shadow-2xl z-40 overflow-hidden flex flex-col max-h-[60vh]"><div className="p-4 bg-gradient-to-l from-[#7A5A16] to-[#D4AF37] text-white"><div className="font-black">مساعد عروضكم V3 🌍</div><div className="text-[11px] opacity-90">يقارن أسعار + يعرف موقعك + يقرأ باركود</div></div><div className="flex-1 overflow-y-auto p-3 space-y-2 bg-[#FFFCF6]">{assistantMsgs.map((m,i)=><div key={i} className={`max-w-[85%] p-3 rounded-2xl text-[13px] ${m.role==='user'?'bg-black text-white mr-auto rounded-br-sm':'bg-white border ml-auto rounded-bl-sm'}`}>{m.text}</div>)}</div><div className="p-3 border-t flex gap-2"><input value={assistantInput} onChange={e=>setAssistantInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&askAssistant()} placeholder="وين أرخص؟ أو صور باركود؟" className="flex-1 h-11 rounded-full border-2 px-4 text-sm"/><button onClick={askAssistant} className="w-11 h-11 rounded-full bg-black text-white">➤</button></div></div>)}
{toast&&<div className="fixed bottom-6 left-1/2 -translate-x-1/2 bg-[#1F1B16] text-white px-5 py-2.5 rounded-full text-xs font-bold z-50 shadow-xl">{toast}</div>}
</div>
)
}
