"use client"
import { useEffect, useMemo, useState } from 'react'

type Hero = { store:string; d:number; t:string; p:number; old:number; code:string; img:string; g:string }
type Offer = { id:number; title:string; store:string; category:string; price:number; old_price:number; discount:number; image:string; lat:number; lng:number; city:string; isOwn?:boolean }
type CartItem = Offer & { qty:number }

const CONTACTS = {
  email: "alhkmy11@gmail.com",
  facebook: "https://www.facebook.com/share/1BqEoZmeJQ/",
  x: "https://x.com/hkeeeeem",
  snap: "https://www.snapchat.com/add/maktb24?share_id=C-xFLFscZTA&locale=ar-AE",
  insta: "https://www.instagram.com/alhkmy11?igsh=MmlrYndpMGQzOG1n",
  tiktok: "https://www.tiktok.com/@hkeeeeem?_r=1&_t=ZS-97xbgSgFxMj",
  realEstate: "https://dealapp.sa/ar/profile/67c08063ca5bafdb59e3d8d4"
}

const HERO: Hero[] = [
  { store:'متجر حكيم', d:40, t:'عطر حكيم الملكي + محفظة جلد فاخر', p:399, old:649, code:'HKEEM20', img:'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=900', g:'from-violet-700 via-fuchsia-600 to-indigo-700' },
  { store:'بنده', d:55, t:'سلة التوفير الكبرى', p:89, old:199, code:'PANDA55', img:'https://images.unsplash.com/photo-1542838132-92c53300491e?w=900', g:'from-emerald-600 to-green-700' },
  { store:'جرير', d:45, t:'آيباد برو M2 12.9', p:2199, old:3999, code:'J10', img:'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=900', g:'from-blue-600 to-indigo-700' },
]
const CATS = [{n:'الكل',i:'✨'},{n:'متجر حكيم',i:'💜'},{n:'عروضكم',i:'🛒'},{n:'أفضل المتاجر',i:'🏆'},{n:'إلكترونيات',i:'📱'},{n:'عروض قريبة',i:'📍'},{n:'عروض حراج',i:'🏷️'}]

const OFFERS: Offer[] = [
  { id:1, title:'عطر حكيم الملكي 100مل', store:'متجر حكيم', category:'متجر حكيم', price:199, old_price:349, discount:43, image:'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600', lat:21.5433, lng:39.1728, city:'جدة', isOwn:true },
  { id:2, title:'محفظة جلد + ساعة', store:'متجر حكيم', category:'متجر حكيم', price:399, old_price:619, discount:35, image:'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600', lat:21.545, lng:39.175, city:'جدة', isOwn:true },
  { id:3, title:'سلة التوفير بنده', store:'بنده', category:'عروضكم', price:89, old_price:149, discount:40, image:'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600', lat:21.54, lng:39.17, city:'جدة' },
  { id:4, title:'آيباد برو M2', store:'جرير', category:'إلكترونيات', price:2199, old_price:3999, discount:45, image:'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600', lat:21.55, lng:39.18, city:'جدة' },
  { id:5, title:'كنب مستعمل نظيف', store:'حراج', category:'عروض حراج', price:1200, old_price:2699, discount:55, image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600', lat:21.53, lng:39.16, city:'جدة' },
  { id:6, title:'AirPods Pro', store:'إكسترا', category:'إلكترونيات', price:899, old_price:1299, discount:30, image:'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=600', lat:21.542, lng:39.172, city:'جدة' },
]

function haversine(a:number,b:number,c:number,d:number){const R=6371;const dLat=(c-a)*Math.PI/180;const dLon=(d-b)*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}

export default function Page(){
  const [a,setA]=useState(0);const [cat,setCat]=useState('الكل');const [cart,setCart]=useState<CartItem[]>([]);const [toast,setT]=useState('');const [font,setFont]=useState<'sm'|'md'|'lg'>('md');const [dark,setDark]=useState(false);const [showF,setShowF]=useState(false);const [showCart,setShowCart]=useState(false);const [showLogin,setShowLogin]=useState(false);const [showShare,setShowShare]=useState<any>(null);const [showContact,setShowContact]=useState(false);const [showDash,setShowDash]=useState(false)
  const [phone,setPhone]=useState('');const [otp,setOtp]=useState('');const [otpSent,setOtpSent]=useState(false);const [timer,setTimer]=useState(0);const [user,setUser]=useState<any>(null)
  const [loc,setLoc]=useState<any>(null);const [nearby,setNearby]=useState(false)

  useEffect(()=>{const t=setInterval(()=>setA(x=>(x+1)%HERO.length),4000);return()=>clearInterval(t)},[])
  useEffect(()=>{if(timer>0){const id=setTimeout(()=>setTimer(timer-1),1000);return()=>clearTimeout(id)}},[timer])
  useEffect(()=>{try{const f=localStorage.getItem('aro_font') as any;if(f) setFont(f);const d=localStorage.getItem('aro_dark');if(d) setDark(d==='1');const c=localStorage.getItem('aro_cart');if(c) setCart(JSON.parse(c));const u=localStorage.getItem('aro_user');if(u) setUser(JSON.parse(u));const l=localStorage.getItem('aro_loc');if(l) setLoc(JSON.parse(l))}catch{}},[])
  useEffect(()=>{localStorage.setItem('aro_font',font)},[font]);useEffect(()=>{localStorage.setItem('aro_dark',dark?'1':'0')},[dark]);useEffect(()=>{localStorage.setItem('aro_cart',JSON.stringify(cart))},[cart])

  const show=(m:string)=>{setT(m);setTimeout(()=>setT(''),2600)}
  const requestLocation=()=>{if(!navigator.geolocation){show('المتصفح لا يدعم الموقع');return}setLoc({loading:true});navigator.geolocation.getCurrentPosition(p=>{const v={lat:p.coords.latitude,lng:p.coords.longitude,city:'جدة',enabled:true,loading:false};setLoc(v);localStorage.setItem('aro_loc',JSON.stringify(v));show('تم تفعيل موقعك في جدة ✓')},()=>{show('فعّل GPS')},{enableHighAccuracy:true})}
  const filtered=useMemo(()=>{let l=cat==='الكل'?OFFERS:cat==='عروض قريبة'?OFFERS:cat==='أفضل المتاجر'?[]:OFFERS.filter(o=>o.category===cat);if((cat==='عروض قريبة'||nearby)&&loc?.enabled){l=[...OFFERS].map(o=>({...o,_d:haversine(loc.lat,loc.lng,o.lat,o.lng)} as any)).sort((a:any,b:any)=>a._d-b._d) as any;if(nearby) l=(l as any).filter((o:any)=>o._d<10)}return l},[cat,loc,nearby])
  const count=cart.reduce((s,i)=>s+i.qty,0);const total=cart.reduce((s,i)=>s+i.price*i.qty,0)
  const add=(o:Offer)=>{setCart(p=>{const f=p.find(x=>x.id===o.id);if(f) return p.map(x=>x.id===o.id?{...x,qty:x.qty+1}:x);return [...p,{...o,qty:1}]});show('أضيف للسلة ✓')}
  const sendOtp=()=>{if(!/^0?5\d{8}$/.test(phone.replace('+966','0'))){show('رقم غير صحيح 05xxxxxxxx');return}setOtpSent(true);setTimer(60);show('رمزك: 1234 (تجريبي)')}
  const verify=()=>{if(otp!=='1234'){show('رمز خاطئ جرب 1234');return}const u={name:'محسن الحكمي',phone,verified:true,points:150};setUser(u);localStorage.setItem('aro_user',JSON.stringify(u));setShowLogin(false);setOtpSent(false);show('تم التحقق ✓')}

  const txt=(it:any)=>`🔥 ${it.title||it.t} - ${it.price||it.p} ر.س بدل ${it.old_price||it.old} (خصم ${it.discount||it.d}%) من ${it.store} عبر عروضكم 💜 https://e2.vercel.app?offer=${it.id||it.code} 🏡 مكتب محسن: ${CONTACTS.realEstate}`
  const share=(k:string)=>{if(!showShare) return;const t=txt(showShare);const u=`https://e2.vercel.app?offer=${showShare.id||showShare.code}`;if(k==='wa') window.open(`https://wa.me/?text=${encodeURIComponent(t)}`);else if(k==='tg') window.open(`https://t.me/share/url?url=${encodeURIComponent(u)}&text=${encodeURIComponent(t)}`);else if(k==='fb') window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(u)}`);else if(k==='x') window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(t)}`);else if(k==='insta'){navigator.clipboard.writeText(t);window.open(CONTACTS.insta,'_blank');show('تم النسخ - افتح انستقرام')}else if(k==='tiktok'){navigator.clipboard.writeText(t);window.open(CONTACTS.tiktok,'_blank');show('تم النسخ - افتح تيك توك')}else if(k==='snap'){navigator.clipboard.writeText(t);window.open(CONTACTS.snap,'_blank');show('تم النسخ - افتح سناب')}else{navigator.clipboard.writeText(t);show('تم النسخ ✓');setShowShare(null)}}

  const fontCls=font==='sm'?'text-[15.5px] leading-7':font==='lg'?'text-[20px] leading-9':'text-[17.5px] leading-8'
  return(<div dir="rtl" className={`min-h-screen ${fontCls} ${dark?'bg-zinc-950 text-zinc-100':'bg-[#FFFBFF] text-zinc-900'}`}>
    <header className={`sticky top-0 z-30 backdrop-blur border-b ${dark?'bg-zinc-900/90 border-zinc-800':'bg-white/90 border-violet-100'}`}><div className="max-w-7xl mx-auto px-4 h-[68px] flex justify-between items-center"><div className="font-black text-[22px]">عروض<span className="text-[#6D28D9]">كم</span></div><div className="flex gap-2 items-center"><div className="relative"><button onClick={()=>setShowF(!showF)} className={`w-11 h-11 rounded-full border font-black grid place-items-center ${dark?'bg-zinc-800 border-zinc-700':'bg-white'}`}>أأ</button>{showF&&<div className={`absolute left-0 top-12 w-44 rounded-2xl border shadow-xl p-2 z-50 ${dark?'bg-zinc-900 border-zinc-700':'bg-white'}`}><button onClick={()=>{setFont('sm');setShowF(false)}} className={`w-full h-11 rounded-full font-bold ${font==='sm'?'bg-[#6D28D9] text-white':'bg-zinc-100 dark:bg-zinc-800'}`}>صغير</button><button onClick={()=>{setFont('md');setShowF(false)}} className={`w-full h-11 mt-1.5 rounded-full font-bold ${font==='md'?'bg-[#6D28D9] text-white':'bg-zinc-100 dark:bg-zinc-800'}`}>متوسط</button><button onClick={()=>{setFont('lg');setShowF(false)}} className={`w-full h-11 mt-1.5 rounded-full font-bold ${font==='lg'?'bg-[#6D28D9] text-white':'bg-zinc-100 dark:bg-zinc-800'}`}>كبير</button></div>}</div><button onClick={()=>setDark(!dark)} className="w-11 h-11 rounded-full border grid place-items-center bg-white dark:bg-zinc-800">{dark?'☀️':'🌙'}</button><button onClick={requestLocation} className={`hidden md:flex h-11 px-4 rounded-full border font-bold ${loc?.enabled?'bg-emerald-600 text-white':'bg-white dark:bg-zinc-800'}`}>{loc?.enabled?'جدة ✓':'تفعيل الموقع 📍'}</button><button onClick={()=>user?setShowDash(true):setShowLogin(true)} className="h-11 px-4 rounded-full border bg-white dark:bg-zinc-800 font-bold">{user?user.phone.slice(-4):'دخول'}</button><button onClick={()=>setShowCart(true)} className="h-11 px-5 rounded-full bg-gradient-to-r from-violet-700 to-fuchsia-600 text-white font-black">السلة {count}</button></div></div></header>

    <main className="max-w-7xl mx-auto px-3">
      <div className="mt-4 relative h-[54vh] rounded-[32px] overflow-hidden bg-black text-white">{HERO.map((s,i)=><div key={i} className={`absolute inset-0 transition-opacity duration-700 ${i===a?'opacity-100':'opacity-0'}`}><div className={`absolute inset-0 bg-gradient-to-r ${s.g}`}/><div className="relative h-full flex flex-col md:flex-row p-8 gap-6 items-center"><div className="flex-1 space-y-3"><span className="px-3 py-1 rounded-full bg-white text-black text-[13px] font-bold">{s.store}</span><div className="text-[54px] font-black leading-none">خصم {s.d}%</div><div className="text-[24px] font-bold">{s.t}</div><div className="flex gap-2"><button onClick={()=>{const o=OFFERS.find(x=>x.store===s.store)||OFFERS[0];add(o)}} className="px-7 h-12 rounded-full bg-white text-black font-black">احصل الآن</button><button onClick={()=>setShowShare(s)} className="px-6 h-12 rounded-full bg-white/20 border border-white/30 font-bold">مشاركة ↗</button></div></div><img src={s.img} className="w-[88%] md:w-[42%] h-56 md:h-full object-cover rounded-[24px]"/></div></div>)}</div>

      <div className="mt-6 flex gap-2 overflow-x-auto py-2">{CATS.map(c=><button key={c.n} onClick={()=>setCat(c.n)} className={`whitespace-nowrap px-5 h-11 rounded-full border font-bold ${cat===c.n?'bg-[#6D28D9] text-white border-[#6D28D9]':'bg-white dark:bg-zinc-900 border-violet-100 dark:border-zinc-800'}`}>{c.i} {c.n}</button>)}</div>

      {loc?.enabled&&<div className="mt-3 flex gap-2 items-center"><label className="flex gap-2 items-center font-bold cursor-pointer"><input type="checkbox" checked={nearby} onChange={e=>setNearby(e.target.checked)} className="w-5 h-5 accent-violet-600"/> العروض القريبة فقط (&lt;10كم)</label><span className="text-[13px] opacity-60">{loc.lat.toFixed(3)},{loc.lng.toFixed(3)}</span></div>}

      <div className="mt-6 grid md:grid-cols-[1fr_360px] gap-6 pb-24">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{filtered.map((o:any)=>{const d=loc?.enabled?haversine(loc.lat,loc.lng,o.lat,o.lng):null;return(<div key={o.id} className={`rounded-[24px] border overflow-hidden ${dark?'bg-zinc-900 border-zinc-800':'bg-white border-violet-100'}`}><div className="relative"><img src={o.image} className="h-52 w-full object-cover"/><span className="absolute top-3 right-3 px-3 py-1 rounded-full bg-[#6D28D9] text-white font-black text-[13px]">-{o.discount}%</span>{d!==null&&<span className="absolute top-3 left-12 px-2.5 py-1 rounded-full bg-emerald-600 text-white text-[11px] font-bold">يبعد {d.toFixed(1)} كم</span>}<button onClick={()=>setShowShare(o)} className="absolute top-3 left-3 w-9 h-9 rounded-full bg-white/90 grid place-items-center">↗</button></div><div className="p-4"><div className="opacity-60 text-[12px] font-bold">{o.store} • {o.city}</div><div className="font-black mt-1 leading-7">{o.title}</div><div className="flex justify-between items-center mt-3"><span className="font-black text-[#7C3AED] text-[19px]">{o.price} ر.س</span><button onClick={()=>add(o)} className="w-11 h-11 rounded-full bg-zinc-900 dark:bg-white dark:text-black text-white font-black text-[20px]">+</button></div></div></div>)})}</div>

        <aside className="space-y-4">
          <div className={`rounded-[24px] border p-5 ${dark?'bg-zinc-900 border-zinc-800':'bg-white'}`}><h3 className="font-black text-[18px]">💜 مشاركة سريعة</h3><div className="grid grid-cols-4 gap-2 mt-3"><button onClick={()=>window.open(CONTACTS.insta)} className="h-11 rounded-full bg-gradient-to-br from-pink-500 to-orange-400 text-white font-bold">IG</button><button onClick={()=>window.open(CONTACTS.tiktok)} className="h-11 rounded-full bg-black text-white font-bold">TT</button><button onClick={()=>window.open(CONTACTS.facebook)} className="h-11 rounded-full bg-[#1877F2] text-white font-bold">FB</button><button onClick={()=>window.open(CONTACTS.snap)} className="h-11 rounded-full bg-[#FFFC00] font-black">SN</button></div></div>
          <div className="rounded-[24px] p-6 text-white bg-gradient-to-br from-[#1A1033] via-[#3B1F75] to-[#6D28D9]"><h3 className="font-black text-[18px]">🏡 مكتبي العقاري</h3><p className="leading-8 mt-2 opacity-95">استقبال طلباتكم في جدة ومكة - محسن الحكمي</p><a href={CONTACTS.realEstate} target="_blank" className="mt-4 inline-flex h-12 px-6 rounded-full bg-white text-[#4C1D95] font-black">فتح الملف ↗</a><div className="mt-3 text-[12px] opacity-80"><a href={`mailto:${CONTACTS.email}`}>{CONTACTS.email}</a></div></div>
          <div className={`rounded-[24px] border p-5 ${dark?'bg-zinc-900 border-zinc-800':'bg-white'}`}><h3 className="font-black">📍 الموقع</h3>{loc?.enabled?<div className="mt-2 leading-7"><div>جدة - مفعّل ✓</div><div className="text-[13px] opacity-70">{loc.lat.toFixed(4)},{loc.lng.toFixed(4)}</div></div>:<><p className="opacity-70 leading-7 text-[14px]">فعّل موقعك لتشوف العروض الأقرب</p><button onClick={requestLocation} className="w-full mt-3 h-12 rounded-full bg-emerald-600 text-white font-black">تفعيل الآن 📍</button></>}</div>
        </aside>
      </div>
    </main>

    {showCart&&<div className="fixed inset-0 z-50 bg-black/60 grid place-items-end md:place-items-center p-0 md:p-4" onClick={()=>setShowCart(false)}><div className={`w-full md:max-w-[440px] max-h-[90vh] rounded-t-[28px] md:rounded-[28px] p-5 flex flex-col ${dark?'bg-zinc-900':'bg-white'}`} onClick={e=>e.stopPropagation()}><h2 className="font-black text-[20px]">السلة {count}</h2><div className="flex-1 overflow-auto mt-4 space-y-3">{cart.map(i=><div key={i.id} className="flex gap-3 border-b pb-3"><img src={i.image} className="w-20 h-20 rounded-2xl object-cover"/><div className="flex-1"><div className="font-bold leading-6">{i.title}</div><div className="flex gap-2 mt-1 items-center"><button onClick={()=>setCart(p=>p.map(x=>x.id===i.id?{...x,qty:Math.max(1,x.qty-1)}:x))} className="w-8 h-8 rounded-full bg-zinc-100 dark:bg-zinc-800">-</button><span className="font-bold w-6 text-center">{i.qty}</span><button onClick={()=>setCart(p=>p.map(x=>x.id===i.id?{...x,qty:x.qty+1}:x))} className="w-8 h-8 rounded-full bg-zinc-100 dark:bg-zinc-800">+</button><span className="mr-2 font-black text-violet-600">{i.price*i.qty} ر.س</span></div></div><button onClick={()=>setCart(p=>p.filter(x=>x.id!==i.id))} className="text-red-500 text-[12px] font-bold">حذف</button></div>)}</div><div className="border-t pt-4"><div className="flex justify-between font-black text-[18px]"><span>الإجمالي</span><span>{total} ر.س</span></div><button onClick={()=>{show('تم الطلب ✓');setCart([]);setShowCart(false)}} className="w-full mt-3 h-12 rounded-full bg-gradient-to-r from-violet-700 to-fuchsia-600 text-white font-black">إتمام الشراء</button></div></div></div>}

    {showLogin&&<div className="fixed inset-0 z-50 bg-black/60 grid place-items-center p-4" onClick={()=>setShowLogin(false)}><div className={`w-full max-w-[400px] rounded-[28px] p-6 ${dark?'bg-zinc-900':'bg-white'}`} onClick={e=>e.stopPropagation()}><h2 className="font-black text-[22px]">التسجيل برقم الجوال</h2>{!otpSent?<><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="05xxxxxxxx" className={`w-full mt-5 h-13 px-5 rounded-full border text-[18px] font-bold outline-none ${dark?'bg-zinc-800 border-zinc-700':'bg-zinc-50'}`}/><button onClick={sendOtp} className="w-full mt-3 h-12 rounded-full bg-[#6D28D9] text-white font-black">إرسال رمز التحقق</button></>:<><input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="1234" maxLength={4} className={`w-full mt-5 h-13 px-5 rounded-full border text-center text-[20px] font-black tracking-[0.4em] ${dark?'bg-zinc-800':'bg-zinc-50'}`}/><div className="flex justify-between mt-2 text-[13px]"><span>الرمز: 1234</span><span className="text-violet-600 font-bold">{timer>0?`${timer}ث`:'إعادة الإرسال'}</span></div><button onClick={verify} className="w-full mt-3 h-12 rounded-full bg-gradient-to-r from-violet-700 to-fuchsia-600 text-white font-black">تأكيد ✓</button><button disabled={timer>0} onClick={sendOtp} className="w-full mt-2 h-11 rounded-full border font-bold disabled:opacity-40">إعادة الإرسال</button></>}<button onClick={()=>setShowLogin(false)} className="w-full mt-3 h-11 rounded-full bg-zinc-100 dark:bg-zinc-800 font-bold">إلغاء</button></div></div>}

    {showShare&&<div className="fixed inset-0 z-50 bg-black/60 grid place-items-center p-4" onClick={()=>setShowShare(null)}><div className={`w-full max-w-[420px] rounded-[28px] p-6 ${dark?'bg-zinc-900':'bg-white'}`} onClick={e=>e.stopPropagation()}><h3 className="font-black text-[18px]">مشاركة العرض 💜</h3><div className="grid grid-cols-2 gap-2.5 mt-5"><button onClick={()=>share('wa')} className="h-12 rounded-full bg-[#25D366] text-white font-black">واتساب</button><button onClick={()=>share('tg')} className="h-12 rounded-full bg-[#229ED9] text-white font-black">تيليجرام</button><button onClick={()=>share('fb')} className="h-12 rounded-full bg-[#1877F2] text-white font-black">فيسبوك</button><button onClick={()=>share('x')} className="h-12 rounded-full bg-black text-white font-black">X</button><button onClick={()=>share('snap')} className="h-12 rounded-full bg-[#FFFC00] text-black font-black">سناب</button><button onClick={()=>share('insta')} className="h-12 rounded-full bg-gradient-to-r from-pink-500 to-orange-400 text-white font-black">انستقرام</button><button onClick={()=>share('tiktok')} className="h-12 rounded-full bg-zinc-900 text-white font-black">تيك توك</button><button onClick={()=>share('copy')} className="col-span-2 h-12 rounded-full border-2 font-black">نسخ الرابط</button></div></div></div>}

    {showContact&&<div className="fixed inset-0 z-50 bg-black/60 grid place-items-center p-4" onClick={()=>setShowContact(false)}><div className={`w-full max-w-[520px] rounded-[28px] p-7 ${dark?'bg-zinc-900':'bg-white'}`} onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="font-black text-[22px]">تواصل معنا</h2><button onClick={()=>setShowContact(false)} className="w-10 h-10 rounded-full bg-zinc-100 dark:bg-zinc-800">✕</button></div><div className="mt-6 grid gap-3"><a href={`mailto:${CONTACTS.email}`} className="h-14 px-5 rounded-full border flex items-center gap-3 font-bold">✉️ {CONTACTS.email}</a><a href={CONTACTS.facebook} target="_blank" className="h-14 px-5 rounded-full bg-[#1877F2] text-white flex items-center font-bold">فيسبوك ↗</a><a href={CONTACTS.x} target="_blank" className="h-14 px-5 rounded-full bg-black text-white flex items-center font-bold">X @hkeeeeem ↗</a><a href={CONTACTS.snap} target="_blank" className="h-14 px-5 rounded-full bg-[#FFFC00] text-black flex items-center font-black">سناب ↗</a><a href={CONTACTS.insta} target="_blank" className="h-14 px-5 rounded-full bg-gradient-to-r from-pink-500 to-orange-400 text-white flex items-center font-bold">انستقرام ↗</a><a href={CONTACTS.tiktok} target="_blank" className="h-14 px-5 rounded-full bg-zinc-900 text-white flex items-center font-bold">تيك توك ↗</a><a href={CONTACTS.realEstate} target="_blank" className="h-14 px-5 rounded-full bg-gradient-to-r from-violet-700 to-fuchsia-600 text-white flex items-center font-black">مكتبي العقاري ↗</a></div></div></div>}

    {showDash&&user&&<div className="fixed inset-0 z-50 bg-black/60 grid place-items-center p-4" onClick={()=>setShowDash(false)}><div className={`w-full max-w-[360px] rounded-[24px] p-6 ${dark?'bg-zinc-900':'bg-white'}`} onClick={e=>e.stopPropagation()}><div className="font-black text-[18px]">{user.name}</div><div className="opacity-60 text-[13px]">{user.phone} • موثق ✓</div><div className="mt-4 p-3 rounded-2xl bg-violet-50 dark:bg-violet-950/30 border">النقاط: <b>{user.points}</b></div><button onClick={()=>{setUser(null);localStorage.removeItem('aro_user');setShowDash(false)}} className="w-full mt-4 h-11 rounded-full border font-bold">خروج</button></div></div>}

    <footer className={`border-t py-6 mt-8 ${dark?'border-zinc-800':'border-violet-100'}`}><div className="max-w-7xl mx-auto px-4 flex gap-2 flex-wrap"><button onClick={()=>setShowContact(true)} className="h-10 px-4 rounded-full border font-bold">تواصل معنا</button><a href={`mailto:${CONTACTS.email}`} className="h-10 px-4 rounded-full border grid place-items-center font-bold">{CONTACTS.email}</a></div></footer>
    {toast&&<div className="fixed bottom-6 left-1/2 -translate-x-1/2 bg-zinc-900 text-white px-6 py-3 rounded-full font-bold z-50">{toast}</div>}
  </div>)
    }
