'use client'
import { useState, useRef, useEffect } from 'react'
const WHATSAPP='966565604856';const DISPLAY='0565604856';const DEALAPP='https://dealapp.sa/ar/profile/67c08063ca5bafdb59e3d8d4?utm_source=visit_my_profile'
export default function OfficeTab(){
const [msgs,setMsgs]=useState<any[]>([{role:'assistant',text:'أهلاً بك في مؤسسة محسن لخدمات الأعمال 👋\nأنا المساعد الذكي، أقدر أساعدك تطلب عقار أو تعرض عقارك.'}])
const [input,setInput]=useState('');const [flow,setFlow]=useState('idle');const [step,setStep]=useState(0);const [data,setData]=useState<any>({})
const bottomRef=useRef<HTMLDivElement>(null);useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:'smooth'})})
const push=(m:any)=>setMsgs(p=>[...p,m])
const start=(t:'طلب'|'عرض')=>{setFlow(t);setStep(0);setData({type:t});if(t==='طلب'){push({role:'user',text:'أبغى أطلب عقار'});push({role:'assistant',text:'وش نوع العقار؟ شقة - فيلا - أرض - استراحة'})}else{push({role:'user',text:'عندي عقار للعرض'});push({role:'assistant',text:'وش نوع عقارك؟ شقة - فيلا - أرض - عمارة'})}}
const send=()=>{if(!input.trim())return;const txt=input.trim();push({role:'user',text:txt});setInput('');if(flow==='طلب'){if(step===0){setData({...data,النوع:txt});push({role:'assistant',text:'في أي مدينة وحي؟ مثال: جدة - الروضة'});setStep(1)}else if(step===1){setData({...data,الموقع:txt});push({role:'assistant',text:'كم ميزانيتك؟'});setStep(2)}else{const f={...data,الميزانية:txt};setData(f);push({role:'assistant',text:`✅ تم حفظ طلبك\nالنوع: ${f.النوع}\nالموقع: ${f.الموقع}\nالميزانية: ${f.الميزانية}\nجاهز للإرسال ${DISPLAY}`});setStep(3)}}else if(flow==='عرض'){if(step===0){setData({...data,النوع:txt});push({role:'assistant',text:'وين موقع العقار؟'});setStep(1)}else if(step===1){setData({...data,الموقع:txt});push({role:'assistant',text:'المساحة والسعر؟'});setStep(2)}else{const f={...data,التفاصيل:txt};setData(f);push({role:'assistant',text:`✅ تم حفظ عرضك\n${f.النوع} - ${f.الموقع}\n${f.التفاصيل}`});setStep(3)}}else{push({role:'assistant',text:'اختر طلب أو عرض من الأزرار فوق'})}}
const waLink=()=>{const t=encodeURIComponent(`السلام عليكم جايك من متجر حكيم\n${Object.entries(data).map(([k,v])=>`${k}: ${v}`).join('\n')}\n${DEALAPP}`);return `https://wa.me/${WHATSAPP}?text=${t}`}
return(<div className="space-y-4 pb-24 p-3">
<div className="rounded-3xl bg-black text-white p-5"><div className="flex gap-3"><div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-[#D4AF37] to-[#7A5A16] grid place-items-center font-black text-xl">م</div><div><h2 className="font-black">مؤسسة محسن لخدمات الأعمال</h2><p className="text-xs text-white/70">محسن الحكمي • وسيط معتمد ✅ مرخص فال</p></div></div><div className="grid grid-cols-3 gap-2 mt-4"><a href={DEALAPP} target="_blank" className="h-10 rounded-full bg-white text-black grid place-items-center text-xs font-black">DealApp ملفي</a><a href={`https://wa.me/${WHATSAPP}`} target="_blank" className="h-10 rounded-full bg-[#25D366] text-white grid place-items-center text-xs font-black">واتساب {DISPLAY}</a><a href={`tel:${DISPLAY}`} className="h-10 rounded-full bg-white/10 border border-white/20 text-white grid place-items-center text-xs">اتصال</a></div></div>
<div className="bg-white rounded-2xl border"><div className="h-11 flex justify-between items-center bg-gradient-to-r from-[#7A5A16] to-[#D4AF37] rounded-xl m-2 px-3 text-white text-sm font-bold"><span>🤖 المساعد العقاري الذكي</span><span className="text-[10px] bg-black/20 px-2 py-1 rounded-full">متصل</span></div><div className="flex gap-2 px-3 overflow-x-auto"><button onClick={()=>start('طلب')} className="px-4 h-9 rounded-full bg-black text-white text-xs font-bold">🔍 أطلب عقار</button><button onClick={()=>start('عرض')} className="px-4 h-9 rounded-full bg-[#FFF3CC] border text-xs font-bold">🏠 أعرض عقاري</button></div><div className="h-[320px] overflow-y-auto mt-3 space-y-2 bg-[#FFFCF6] p-3 rounded-xl">{msgs.map((m,i)=><div key={i} className={`flex ${m.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[85%] rounded-2xl px-3 py-2 text-sm whitespace-pre-wrap ${m.role==='user'?'bg-black text-white':'bg-white border shadow-sm'}`}>{m.text}</div></div>)}{step===3&&<div className="grid grid-cols-2 gap-2"><a href={waLink()} target="_blank" className="h-11 rounded-full bg-[#25D366] text-white grid place-items-center font-black text-sm">إرسال واتساب ✅</a><a href={DEALAPP} target="_blank" className="h-11 rounded-full bg-black text-white grid place-items-center text-sm">فتح ملفي</a></div>}<div ref={bottomRef}/></div><div className="flex gap-2 p-2 border-t"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="اكتب هنا..." className="flex-1 h-11 rounded-full bg-[#F5F1E8] border px-4 text-sm outline-none"/><button onClick={send} className="w-11 h-11 rounded-full bg-black text-white font-black">↑</button></div></div></div>)}
