'use client'
import { useState, useRef, useEffect } from 'react'
const WHATSAPP='966565604856';const DISPLAY='0565604856';const DEALAPP='https://dealapp.sa/ar/profile/67c08063ca5bafdb59e3d8d4'
export default function OfficeTab(){
const [msgs,setMsgs]=useState<any[]>([{role:'assistant',text:'أهلاً بك في مؤسسة محسن لخدمات الأعمال 👋\nأقدر أساعدك تطلب عقار أو تعرض عقارك.'}])
const [input,setInput]=useState('');const [flow,setFlow]=useState('idle');const [step,setStep]=useState(0);const [data,setData]=useState<any>({})
const bottomRef=useRef<HTMLDivElement>(null);useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:'smooth'})})
const push=(m:any)=>setMsgs(p=>[...p,m])
const start=(t:'طلب'|'عرض')=>{setFlow(t);setStep(0);setData({type:t});push({role:'user',text:t==='طلب'?'أبغى أطلب عقار':'عندي عقار للعرض'});push({role:'assistant',text:t==='طلب'?'وش نوع العقار؟ شقة - فيلا - أرض':'وش نوع عقارك؟'})}
const send=()=>{if(!input.trim())return;const txt=input.trim();push({role:'user',text:txt});setInput('');if(step===0){setData({...data,النوع:txt});push({role:'assistant',text:'وين الموقع؟'});setStep(1)}else if(step===1){setData({...data,الموقع:txt});push({role:'assistant',text:'الميزانية أو التفاصيل؟'});setStep(2)}else{setData({...data,التفاصيل:txt});push({role:'assistant',text:`✅ تم الحفظ\nجاهز للإرسال واتساب ${DISPLAY}`});setStep(3)}}
const wa=()=>{const t=encodeURIComponent(`جايك من متجر حكيم\n${Object.entries(data).map(([k,v])=>`${k}:${v}`).join('\n')}\n${DEALAPP}`);return `https://wa.me/${WHATSAPP}?text=${t}`}
return(<div className="space-y-4 pb-24 p-3"><div className="rounded-3xl bg-black text-white p-5"><h2 className="font-black">مؤسسة محسن لخدمات الأعمال</h2><p className="text-xs text-white/70">محسن الحكمي • وسيط معتمد ✅ مرخص فال</p><div className="grid grid-cols-3 gap-2 mt-4"><a href={DEALAPP} target="_blank" className="h-10 rounded-full bg-white text-black grid place-items-center text-xs font-black">DealApp</a><a href={`https://wa.me/${WHATSAPP}`} target="_blank" className="h-10 rounded-full bg-[#25D366] text-white grid place-items-center text-xs font-black">{DISPLAY}</a><a href={`tel:${DISPLAY}`} className="h-10 rounded-full bg-white/10 border text-white grid place-items-center text-xs">اتصال</a></div></div><div className="bg-white rounded-2xl border p-2"><div className="flex gap-2"><button onClick={()=>start('طلب')} className="px-4 h-9 rounded-full bg-black text-white text-xs font-bold">🔍 أطلب</button><button onClick={()=>start('عرض')} className="px-4 h-9 rounded-full bg-[#FFF3CC] border text-xs font-bold">🏠 أعرض</button></div><div className="h-[300px] overflow-y-auto mt-2 space-y-2 bg-[#FFFCF6] p-2 rounded-xl">{msgs.map((m,i)=><div key={i} className={`flex ${m.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[85%] rounded-2xl px-3 py-2 text-sm whitespace-pre-wrap ${m.role==='user'?'bg-black text-white':'bg-white border'}`}>{m.text}</div></div>)}{step===3&&<a href={wa()} target="_blank" className="h-11 rounded-full bg-[#25D366] text-white grid place-items-center font-black">إرسال واتساب ✅</a>}<div ref={bottomRef}/></div><div className="flex gap-2 mt-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="اكتب..." className="flex-1 h-11 rounded-full bg-[#F5F1E8] border px-4 text-sm"/><button onClick={send} className="w-11 h-11 rounded-full bg-black text-white">↑</button></div></div></div>)}
